/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { useCylinder } from "@react-three/cannon";

export default function Model({ ...props }) {
  const [ref] = useCylinder(() => ({ mass: 10000, ...props }));
  const { nodes } = useGLTF("/rockColumn.gltf");

  return (
    <mesh
      rotation={[-Math.PI / 2, 0, 0]}
      ref={ref}
      dispose={null}
      geometry={nodes.obj_57937915.geometry}
      material={nodes.obj_57937915.material}
      onClick={(e) => {
        e.stopPropagation();
      }}
    >
      <meshNormalMaterial />
    </mesh>
  );
}

useGLTF.preload("/RockColumn.gltf");
